## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Basically in  Python, the variable types list and array_list are not same at all. The built-in data type is list, which represents an ordered collection of items. However, array_list could be a custom variable name, so without further information, we cannot determine its exact data type.

In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [2]:
type(list_)

list

In [3]:
type(array_list)

numpy.ndarray

## Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [4]:
for i in list_:
    print("The DataType is: ",type(i))

The DataType is:  <class 'str'>
The DataType is:  <class 'str'>
The DataType is:  <class 'str'>
The DataType is:  <class 'str'>
The DataType is:  <class 'str'>


In [5]:
for j in array_list:
    print("The DataType is: ",type(j))

The DataType is:  <class 'numpy.str_'>
The DataType is:  <class 'numpy.str_'>
The DataType is:  <class 'numpy.str_'>
The DataType is:  <class 'numpy.str_'>
The DataType is:  <class 'numpy.str_'>


## Q3. Considering the following changes in the variable, array_list: 

## array_list = np.array(object = list_, dtype = int) 

## Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

In [6]:
array_list = np.array(object = list_, dtype = int)

Yes when we write the above code we must find the changes in the datatype for the array_list variable nbut the datatype of list_ might same as before.

In [7]:
for i in list_:
    print("The DataType is: ",type(i))   # here we get the datatype is same (string) as before

The DataType is:  <class 'str'>
The DataType is:  <class 'str'>
The DataType is:  <class 'str'>
The DataType is:  <class 'str'>
The DataType is:  <class 'str'>


In [8]:
for j in array_list:
    print("The DataType is: ",type(j))   # But here we can get the different datatype which is integer

The DataType is:  <class 'numpy.int64'>
The DataType is:  <class 'numpy.int64'>
The DataType is:  <class 'numpy.int64'>
The DataType is:  <class 'numpy.int64'>
The DataType is:  <class 'numpy.int64'>


## Q4. Write a code to find the following characteristics of variable, num_array:
## (i) shape
## (ii) size

In [9]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [10]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.shape(num_array)  #Finding the shape of num_array

(2, 3)

In [12]:
num_array.size  #Finding the size of num_array

6

## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [13]:
import numpy as np

# Creating a 3x3 matrix of zeros
zeros_matrix= np.zeros((3, 3))
zeros_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [14]:
import numpy as np

identity_matrix = np.eye(5) #Creating a 5x5 identity matrix

identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])